gov_uk_search_api_url: https://www.gov.uk/api/search.json
gov_uk_search_url: https://www.gov.uk/search
moj_home_page: https://www.gov.uk/government/organisations/ministry-of-justice

correspondence_categories:
  - general_enquiries
  - freedom_of_information_request

feedback_options:
  - strongly_agree
  - agree
  - neither_agree_nor_disagree
  - disagree
  - strongly_disagree

correspondence_topic_max_length: 60
correspondence_message_max_length: 5000

# Variables below are meant to be over-ridden in non-local environments (dev,
# staging, prod) with correct values. The values below are place-holders.

correspondence_email_from: correspondence_tool@localhost
general_enquiries_email: general_enquiries@localhost
freedom_of_information_request_email: foi_request@localhost
aaq_feedback_email: feedback@localhost
aaq_email_url: http://localhost:3000

# These are set in run.sh
git_source:  Git Source Not Available
build_date:  Build Date Not Available
git_commit:  Git Commit Not Available

govuk_notify_api_key: ENV['SETTINGS__GOVUK_NOTIFY_API_KEY']
new_correspondence_notify_template: '29ad44f7-ba74-455c-9f8e-e2d72c933620'
correspondence_confirmation_notify_template: 'cfa41a99-a4d0-4a7f-8c69-3d5f097397a0'
new_feedback_notify_template: '2ddca175-7284-4343-9408-a7db23975269'
