gov_uk_search_api_url: https://www.gov.uk/api/search.json
gov_uk_search_url: https://www.gov.uk/search
moj_home_page: https://www.gov.uk/government/organisations/ministry-of-justice

correspondence_categories:
  - general_enquiries
  - freedom_of_information_request
  - smoke_test

feedback_options:
  - strongly_agree
  - agree
  - neither_agree_nor_disagree
  - disagree
  - strongly_disagree

correspondence_topic_max_length: 60

# Variables below are meant to be over-ridden in non-local environments (dev,
# staging, prod) with correct values. The values below are place-holders.
ga_tracking_id: ''

sendgrid_username: sendgrid
sendgrid_password: password

correspondence_email_from: correspondence_tool@localhost
general_enquiries_email: general_enquiries@localhost
freedom_of_information_request_email: foi_request@localhost
smoke_test_email: smoketest@localhost
smoke_tests:
  protocol: !ruby/symbol pop3
  server: 'pop3.local'
  port: 995
  ssl: true
  username: 'smoketest'
  password: 'password'
  first_read_wait: 3
  max_wait_time: 600
aaq_feedback_email: feedback@localhost
aaq_email_url: http://localhost/

# These are set in run.sh
git_source:  Git Source Not Available
build_date:  Build Date Not Available
git_commit:  Git Commit Not Available
