correspondence_types:
  - general_enquiries
  - freedom_of_information_request

correspondence_topics:
  - courts_and_tribunals
  - prisons_and_probation
  - legal_aid
  - something_else

service_feedback:
  - very_satisfied
  - satisfied
  - neither_satisfied_nor_dissatisfied
  - dissatisfied
  - very_dissatisfied

general_enquiries_email: general_enquiries@localhost
freedom_of_information_request_email: foi_request@localhost
